### ISSUE TITLE
Trouble understanding *_comp.txt and *_seg.txt for plane detection.

### ISSUE THREAD

**Issue by zyuanbing** [ThibaultLejemble/Plane-Detection-Point-Cloud#2]
Thanks for the release.
I want to use this code for plane detection. Follow the [instruction](https://github.com/ThibaultLejemble/Plane-Detection-Point-Cloud#usage) I am able to replicate the paper result now. But I don't know exactly which file the plane information is stored in and how to parsing them. 
Anybody give me some hints?

Thanks in advance.

**Comment by nmellado** [comment]
Hi,

I am not expert of this code, but maybe I can help, until @ThibaultLejemble gets more detailed feedback.

Seg files are loaded/saved by this class: https://github.com/ThibaultLejemble/Plane-Detection-Point-Cloud/blob/bc3d55a9c3e605676a056839617d1a7031a0e974/src/PDPC/Segmentation/MSSegmentation.cpp
Comp files are loaded/saved by this class: https://github.com/ThibaultLejemble/Plane-Detection-Point-Cloud/blob/bc3d55a9c3e605676a056839617d1a7031a0e974/src/PDPC/Persistence/ComponentDataSet.cpp, which store data as ComponentSet (https://github.com/ThibaultLejemble/Plane-Detection-Point-Cloud/blob/5a13d58b9eb539b8608bdad7491445898c995e2c/src/PDPC/Persistence/ComponentSet.h).

You can see an example of use here: 
https://github.com/ThibaultLejemble/Plane-Detection-Point-Cloud/blob/a03bbdaa315ce0e9afe69d69fb280572c2052505/app/pdpcPostProcess.cpp#L38-L44

From what I see, planes are not explicitly stored. Components contain a collection of indices, from which I you might be able to get your planes: 
https://github.com/ThibaultLejemble/Plane-Detection-Point-Cloud/blob/5a13d58b9eb539b8608bdad7491445898c995e2c/src/PDPC/Persistence/Component.h#L57

Hope that helps

Nicolas

**Comment by zyuanbing** [comment]
@nmellado Thanks!
It looks like indices of points in the same plane are stored. It might be possible to fit a plane with these points.

**Comment by ThibaultLejemble** [comment]
The file `*_seg.txt` contains a segmentation at multiple scales. 
The first line contains the number of points `N` and the number of scales `M`.
Then there are `N` lines with `M` integers. 
Each integer is a label for one point at one scale. 
This label refers to a component (a plane).
The special label `-1` means that the point is not part of any component at that scale. 

The file `*_comp.txt` contains one component per line. 
Each line start by two integers corresponding to the birth and death level of the component.
Then, there are all the indices of the points that belong to the component.   

The simplest option to get the plane informations is to average the positions and the normal vectors using the points indices of each plane in the file `*_comp.txt`.

Using the data structures of this project gives something like this (not compiled nor tested)
```
#include <PDPC/PointCloud/Loader.h>
#include <PDPC/PointCloud/PointCloud.h>
#include <PDPC/Persistence/ComponentDataSet.h>

using namespace pdpc;

void compute_planes()
{
    PointCloud points;
    Loader::Load("the_point_cloud.ply", points);

    ComponentDataSet comp_data;
    comp_data.load("the_data_file_comp.txt");

    for(int idx_plane=0; idx_plane<comp_data.size(); ++idx_plane)
    {
        Vector3 plane_point  = Vector3::Zero();
        Vector3 plane_normal = Vector3::Zero();

        for(int idx_point : comp_data[idx_plane].indices())
        {
            plane_point  += points.point(idx_point);
            plane_normal += points.normal(idx_point);
        }

        plane_point /= comp_data[idx_plane].indices().size();
        plane_normal.normalize();

        // ...
        // here we have the plane information in the form point + normal vector
        // ...
    }
}
```

**Comment by zyuanbing** [comment]
@ThibaultLejemble Thanks! This is really helpful.
