### ISSUE TITLE
Ransac

### ISSUE THREAD

**Issue by edwinlu-hdu** [ThibaultLejemble/Plane-Detection-Point-Cloud#3]
First of all, thank you very much for your contribution. It is able to detect plane information very robustly. I now want to repeat your experiment part. Among them, part of your control experiment uses the RANSAC method to detect planes. The code of your experiment is easy to send Me? Email : 15946713179@163.com . Thank you very much.

**Comment by nmellado** [comment]
@ThibaultLejemble which RANSAC implementation did you use for comparison in the paper ?

**Comment by edwinlu-hdu** [comment]
Any valid RANSAC will do. For example, as shown in the figure below
![0](https://user-images.githubusercontent.com/68134450/116977476-112c1a00-acf5-11eb-9bea-376d66b2e4bf.png)

**Comment by nmellado** [comment]
For this one we used https://doc.cgal.org/latest/Polygonal_surface_reconstruction/index.html

**Comment by edwinlu-hdu** [comment]
Thank you very much!  Merci beaucoup !
